### ISSUE TITLE
meta

### ISSUE THREAD

**Issue by jamesturk** [jamesturk/scrapeghost#16]
- [x] set up CI
- [x] pre-commit config
- [ ] release script
- [ ] cool ghost logo?
